# CONSTANTS

NUM       = '123456789'
NUMERIC   = '0123456789'
LETTER_S  = 'abcdefghijklmnopqrstuvwxyz'
LETTER_B  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LETTER_A  = f'{LETTER_S}{LETTER_B}'
ALPHA_NUM = f'{LETTER_A}{NUMERIC}'
MOS       = '+-*/%.'
SPXCHAR1  = '!@#$%^&*'
SPXCHAR2  = '()[]{\\}<>'
SPXCHAR3  = '.,:;-_=+'
SPXCHAR4  = '`~|/?!"'
SPXCHAR5  = '\' '
SPXCHAR6  = '\'"`~^_-'
SPXCHAR7  = '€£¥¢$¤₣₧₨₹'
SPECIAL   = f'{SPXCHAR1}{SPXCHAR2}{SPXCHAR3}{SPXCHAR4}{SPXCHAR5}{SPXCHAR6}{SPXCHAR7}'
DELIMID   = f'{MOS} \n=!><()[],}};:'
DELIM1    = ' {'
DELIM2    = ' ('
DELIM3    = '{\n'
DELIM4    = f' \n{ALPHA_NUM}'
DELIM5    = f' {ALPHA_NUM}'
DELIM6    = f' {ALPHA_NUM}"[-]`'
DELIM7    = ' ;+-*/.{,:)]}'
DELIM8    = f'{ALPHA_NUM},{{+-*/.'
DELIM9    = f' ({{{ALPHA_NUM}-'
DELIM10   = ' ;:,({[+-*/<>=])}'
DELIM11   = ' ;,({[+'
DELIM12   = ' \n'
DELIM13   = ' );'
DELIM14   = ' :'
DELIM15   = f' {LETTER_A}'
DELIM16   = f' )"-{ALPHA_NUM}([`'
DELIM17   = ' }"-\n'
DELIM18   = ' );]'