# CONSTANTS

NUM       = '123456789'
NUMERIC   = '0123456789'
LETTER_S  = 'abcdefghijklmnopqrstuvwxyz'
LETTER_B  = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
LETTER_A  = f'{LETTER_S}{LETTER_B}'
ALPHA_NUM = f'{LETTER_A}{NUMERIC}'
MOS       = '+-*/%.'
SPXCHAR1  = '!@#$%^&*'
SPXCHAR2  = '()[]{\\}<>'
SPXCHAR3  = '.,:;-_=+'
SPXCHAR4  = '`~|/?!"'
SPXCHAR5  = '\' '
SPXCHAR6  = '\'"`~^_-'
SPXCHAR7  = '€£¥¢$¤₣₧₨₹'
SPXCHAR8  = '←→↑↓↔↕↖↗↘↙'
SPXCHAR9  = '•◦●○‣⁃∙◆▪▫'
SPXSYMB1  = '©'
SPXSYMB2  = '®'
SPXSYMB3  = '™'
SPECIAL   = f'{SPXCHAR1}{SPXCHAR2}{SPXCHAR3}{SPXCHAR4}{SPXCHAR5}{SPXCHAR6}{SPXCHAR7}{SPXCHAR8}{SPXCHAR9}{SPXSYMB1}{SPXSYMB2}{SPXSYMB3}'
DELIMID   = f'{MOS}; =!><()[],}}:'
DELIM1    = ' {'
DELIM2    = ' ('
DELIM3    = '{\n'
DELIM4    = ' \n'
DELIM5    = f' {NUMERIC}-'
DELIM6    = f' {ALPHA_NUM}'
DELIM7    = ' ;+-*/.{'
DELIM8    = f'{ALPHA_NUM},{{+-*/.'
DELIM9    = f' ({{{ALPHA_NUM}'
DELIM10   = ' ;,({[+-*/<>=])}:'
DELIM11   = ' ;,({[+'
DELIM12   = ' \n'
DELIM13   = ' );'
DELIM14   = ' :'