tokens = [
    Token(1, 'ONBOARD', 'Onboard'),
    Token(2, 'PINT', 'pint'),
    Token(2, 'IDENTIFIER', 'g'),
    Token(2, 'ASSIGN', '='),
    Token(2, 'PINT LIT', '1'),
    Token(2, 'SMCLN', ';'),
    Token(3, 'DOFFY', 'doffy'),
    Token(3, 'IDENTIFIER', 'name'),
    Token(3, 'ASSIGN', '='),
    Token(3, 'DOFFY LIT', 'luwesss'),
    Token(3, 'SMCLN', ';'),
    Token(4, 'CAPTAIN', 'captain'),
    Token(4, 'LPAREN', '('),
    Token(4, 'RPAREN', ')'),
    Token(4, 'LBRACKET', '{'),
    Token(5, 'PINT', 'pint'),
    Token(5, 'IDENTIFIER', 'l'),
    Token(5, 'ASSIGN', '='),
    Token(5, 'PINT LIT', '1'),
    Token(5, 'COMMA', ','),
    Token(5, 'IDENTIFIER', 'll'),
    Token(5, 'ASSIGN', '='),
    Token(5, 'PINT LIT', '2'),
    Token(5, 'SMCLN', ';'),
    Token(6, 'RBRACKET', '}'),
    Token(7, 'OFFBOARD', 'Offboard'),
]

analyze_syntax(tokens)