tokens = [
    Token(1, 'ONBOARD', 'onboard'),
    Token(2, 'PINT', 'pint'),
    Token(2, 'IDENTIFIER', 'x'),
    Token(2, '=', '='),
    Token(2, 'PINT LIT', '10'),
    Token(2, ';', ';'),
    Token(3, 'DOFFY', 'doffy'),
    Token(3, 'IDENTIFIER', 'y'),
    Token(3, '=', '='),
    Token(3, 'DOFFY LIT', 'hello'),
    Token(3, ';', ';'),
    Token(4, 'OFFBOARD', 'offboard')
]

tokens = [
    Token(1, 'ONBOARD', 'onboard'),
    Token(2, 'PINT', 'pint'),
    Token(2, 'IDENTIFIER', 'globalVar'),
    Token(2, '=', '='),
    Token(2, 'PINT LIT', '5'),
    Token(2, ';', ';'),
    Token(3, 'VOID', 'void'),
    Token(3, 'IDENTIFIER', 'subFunction'),
    Token(3, '(', '('),
    Token(3, ')', ')'),
    Token(3, '{', '{'),
    Token(4, 'PINT', 'pint'),
    Token(4, 'IDENTIFIER', 'localVar'),
    Token(4, '=', '='),
    Token(4, 'PINT LIT', '15'),
    Token(4, ';', ';'),
    Token(5, '}', '}'),
    Token(6, 'CAPTAIN', 'captain'),
    Token(6, '(', '('),
    Token(6, ')', ')'),
    Token(6, '{', '{'),
    Token(7, 'IDENTIFIER', 'globalVar'),
    Token(7, '=', '='),
    Token(7, 'PINT LIT', '20'),
    Token(7, ';', ';'),
    Token(8, '}', '}'),
    Token(9, 'OFFBOARD', 'offboard')
]

tokens = [
    Token(1, 'ONBOARD', 'onboard'),
    Token(2, 'PINT', 'pint'),
    Token(2, 'IDENTIFIER', 'i'),
    Token(2, '=', '='),
    Token(2, 'PINT LIT', '0'),
    Token(2, ';', ';'),
    Token(3, 'FOUR', 'four'),
    Token(3, '(', '('),
    Token(3, 'IDENTIFIER', 'i'),
    Token(3, '=', '='),
    Token(3, 'PINT LIT', '0'),
    Token(3, ';', ';'),
    Token(3, 'IDENTIFIER', 'i'),
    Token(3, '<', '<'),
    Token(3, 'PINT LIT', '10'),
    Token(3, ';', ';'),
    Token(3, 'IDENTIFIER', 'i'),
    Token(3, '++', '++'),
    Token(3, ')', ')'),
    Token(3, '{', '{'),
    Token(4, 'FIRE', 'fire'),
    Token(4, '(', '('),
    Token(4, 'IDENTIFIER', 'i'),
    Token(4, ')', ')'),
    Token(4, ';', ';'),
    Token(5, '}', '}'),
    Token(6, 'OFFBOARD', 'offboard')
]

tokens = [
    Token(1, 'ONBOARD', 'onboard'),
    Token(2, 'PINT', 'pint'),
    Token(2, 'IDENTIFIER', 'a'),
    Token(2, '=', '='),
    Token(2, 'PINT LIT', '1'),
    Token(2, ';', ';'),
    Token(3, 'VOID', 'void'),
    Token(3, 'IDENTIFIER', 'subFunction'),
    Token(3, '(', '('),
    Token(3, ')', ')'),
    Token(3, '{', '{'),
    Token(4, 'PINT', 'pint'),
    Token(4, 'IDENTIFIER', 'a'),
    Token(4, '=', '='),
    Token(4, 'PINT LIT', '2'),
    Token(4, ';', ';'),
    Token(5, 'IDENTIFIER', 'a'),
    Token(5, '=', '='),
    Token(5, 'PINT LIT', '3'),
    Token(5, ';', ';'),
    Token(6, '}', '}'),
    Token(7, 'CAPTAIN', 'captain'),
    Token(7, '(', '('),
    Token(7, ')', ')'),
    Token(7, '{', '{'),
    Token(8, 'IDENTIFIER', 'a'),
    Token(8, '=', '='),
    Token(8, 'PINT LIT', '4'),
    Token(8, ';', ';'),
    Token(9, '}', '}'),
    Token(10, 'OFFBOARD', 'offboard')
]

tokens = [
    Token(1, 'ONBOARD', 'onboard'),
    Token(2, 'PINT', 'pint'),
    Token(2, 'IDENTIFIER', 'x'),
    Token(2, '=', '='),
    Token(2, 'PINT LIT', '10'),
    Token(2, ';', ';'),
    Token(3, 'IDENTIFIER', 'x'),
    Token(3, '=', '='),
    Token(3, 'DOFFY LIT', 'string_value'),
    Token(3, ';', ';'),
    Token(4, 'OFFBOARD', 'offboard')
]

tokens = [
    Token(1, 'ONBOARD', 'onboard'),
    Token(2, 'PINT', 'pint'),
    Token(2, 'IDENTIFIER', 'x'),
    Token(2, '=', '='),
    Token(2, 'PINT LIT', '10'),
    Token(2, ';', ';'),
    Token(3, 'PINT', 'pint'),
    Token(3, 'IDENTIFIER', 'add'),
    Token(3, '(', '('),
    Token(3, 'PINT', 'pint'),
    Token(3, 'IDENTIFIER', 'a'),
    Token(3, ',', ','),
    Token(3, 'PINT', 'pint'),
    Token(3, 'IDENTIFIER', 'b'),
    Token(3, ')', ')'),
    Token(3, '{', '{'),
    Token(4, 'HOME', 'home'),
    Token(4, 'IDENTIFIER', 'a'),
    Token(4, '+', '+'),
    Token(4, 'IDENTIFIER', 'b'),
    Token(4, ';', ';'),
    Token(5, '}', '}'),
    Token(6, 'CAPTAIN', 'captain'),
    Token(6, '(', '('),
    Token(6, ')', ')'),
    Token(6, '{', '{'),
    Token(7, 'IDENTIFIER', 'x'),
    Token(7, '=', '='),
    Token(7, 'IDENTIFIER', 'add'),
    Token(7, '(', '('),
    Token(7, 'PINT LIT', '5'),
    Token(7, ',', ','),
    Token(7, 'PINT LIT', '10'),
    Token(7, ')', ')'),
    Token(7, ';', ';'),
    Token(8, '}', '}'),
    Token(9, 'OFFBOARD', 'offboard')
]
